require: rubocop-rails

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'lib/**/*'
    - 'test/**/*'    
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'app/mailers/*'
    - 'app/jobs/*'
    - 'app/helpers/*'
    - 'app/channels/**/*'
